# Generated by Django 5.2.15 on 2026-07-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_commande_atelier_commande_est_fictif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_predit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_predite', models.PositiveIntegerField(help_text='Durée de production prédite, en jours.')),
                ('date_estimation', models.DateTimeField(auto_now_add=True)),
                ('version_modele', models.CharField(default='heuristique-v0', help_text='Identifie si la prediction vient du modele XGBoost entraine ou du repli heuristique (RG20).', max_length=50)),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_ia', to='commandes.devis')),
            ],
            options={
                'verbose_name': 'Estimation IA',
                'verbose_name_plural': 'Estimations IA',
                'db_table': 'estimations_ia',
            },
        ),
    ]
