# Generated by Django 5.2.15 on 2026-07-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MINISTERE', 'Ministère'), ('COLLECTIVITE', 'Collectivité territoriale'), ('ETABLISSEMENT_PUBLIC', 'Établissement public'), ('PARTICULIER', 'Particulier')], max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Organisme client',
                'verbose_name_plural': 'Organismes clients',
                'db_table': 'organismes_clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=15, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('DEVIS', 'Devis en cours'), ('VALIDEE', 'Validée'), ('EN_PRODUCTION', 'En production'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('delai_contractuel', models.DateField(blank=True, help_text='Obligatoire pour les commandes étatiques soumises à marché public (RG19).', null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commandes.organismeclient')),
            ],
            options={
                'db_table': 'commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_revient', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_devis', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='commandes.commande')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devis',
            },
        ),
    ]
