# Generated by Django 5.2.15 on 2026-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='atelier',
            field=models.CharField(choices=[('SPA', 'Service de Production A'), ('SPB', 'Service de Production B')], default='SPA', max_length=5),
        ),
        migrations.AddField(
            model_name='commande',
            name='est_fictif',
            field=models.BooleanField(default=False, help_text="Commande generee artificiellement pour entrainer le modele IA en l'absence d'historique reel."),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_document',
            field=models.CharField(choices=[('JOURNAL_OFFICIEL', 'Journal officiel'), ('BULLETIN_ANNONCES', "Bulletin d'annonces légales"), ('FORMULAIRE_ADMINISTRATIF', 'Formulaire administratif'), ('CACHET_ADMINISTRATIF', 'Cachet administratif'), ('DOCUMENT_FIDUCIAIRE', 'Document fiduciaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30),
        ),
        migrations.AddField(
            model_name='devis',
            name='duree_production',
            field=models.PositiveIntegerField(default=1, help_text='Durée réelle ou estimée de production, en jours.'),
        ),
    ]
