# Generated by Django 5.2.15 on 2026-07-27 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_atelier_commande_est_fictif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('SPA', 'Service de Production A'), ('SPB', 'Service de Production B')], max_length=5, unique=True)),
                ('chef_atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ateliers_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers',
                'db_table': 'ateliers',
            },
        ),
        migrations.CreateModel(
            name='DossierFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut_production', models.CharField(choices=[('CREE', 'Créé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='CREE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='commandes.atelier')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_fabrication', to='commandes.commande')),
            ],
            options={
                'db_table': 'dossiers_fabrication',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='A_FAIRE', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='commandes.dossierfabrication')),
            ],
            options={
                'db_table': 'etapes_production',
                'ordering': ['id'],
            },
        ),
    ]
