# Generated by Django 5.2.15 on 2026-07-28 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_atelier_dossierfabrication_etapeproduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Désignation générique unique (ex. « papier offset », « encre noire »).', max_length=100, unique=True)),
                ('classe_comptable', models.CharField(choices=[('CLASSE_2', 'Classe 2 - Immobilisation'), ('CLASSE_6', 'Classe 6 - Charge / matière première')], default='CLASSE_6', max_length=10)),
                ('type_papier', models.CharField(blank=True, choices=[('OFFSET', 'Offset'), ('DOSSIER', 'Dossier'), ('AUTOCOPIANT', 'Autocopiant'), ('NON_APPLICABLE', 'Non applicable')], default='NON_APPLICABLE', max_length=20)),
                ('type_encre', models.CharField(blank=True, max_length=50)),
                ('type_film', models.CharField(blank=True, max_length=50)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_securite', models.DecimalField(decimal_places=2, default=0, help_text='Stock de sécurité : seuil en-dessous duquel une alerte est déclenchée.', max_digits=12)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='commandes.article')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='commandes.dossierfabrication')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
