# Generated by Django 6.0.7 on 2026-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_article_mouvementstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=30, unique=True)),
                ('valeur', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sequences_compteurs',
            },
        ),
    ]
