# Generated by Django 6.0.7 on 2026-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_sequencecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nature',
            field=models.CharField(choices=[('SUR_CONFECTION', 'Sur confection (sur-mesure)'), ('STANDARDISEE', 'Standardisée (prix fixe)')], default='STANDARDISEE', help_text='Distingue le circuit de devis applique : sur confection (devis au cas par cas) ou standardisee (prix unitaire fixe). Fixee a la creation et non modifiable apres validation du devis (RG21).', max_length=20),
        ),
        migrations.AddField(
            model_name='devis',
            name='duree_contrat_annees',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Durée du contrat à prix fixe, en années (maximum 5).', null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='pluriannuel',
            field=models.BooleanField(default=False, help_text='Marché public à prix unitaire fixe sur plusieurs années.'),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_inflation_projete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux d'inflation annuel moyen projeté (%), calculé sur l'historique des 5 dernières années.", max_digits=5, null=True),
        ),
    ]
