# Generated by Django 5.2.15 on 2026-07-28 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0004_article_mouvementstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_facture', models.CharField(choices=[('PROFORMA', 'Facture proforma'), ('DEFINITIVE', 'Facture définitive')], default='PROFORMA', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='commandes.dossierfabrication')),
                ('emise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_emises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factures',
                'ordering': ['-date_facture'],
            },
        ),
    ]
