# Generated by Django 5.2.17 on 2026-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur.", null=True, upload_to='photos_profil/'),
        ),
    ]
