# Generated by Django 6.0.7 on 2026-08-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('COMMANDE', 'Commande'), ('DOSSIER', 'Dossier de fabrication'), ('ETAPE', 'Étape de production'), ('STOCK', 'Stock')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('reference_objet_id', models.PositiveIntegerField(blank=True, help_text="Identifiant de l'objet concerné (commande, dossier, étape…), pour lien direct côté frontend.", null=True)),
                ('lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
