# Generated by Django 5.2.17 on 2026-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('COMMANDE', 'Commande'), ('DOSSIER', 'Dossier de fabrication'), ('ETAPE', 'Étape de production'), ('STOCK', 'Stock'), ('CONTROLE', 'Contrôle du prix de revient')], max_length=20),
        ),
    ]
