# Generated by Django 5.2.17 on 2026-08-07 09:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0006_commande_nature_devis_duree_contrat_annees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePrixRevient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_matieres_reel', models.DecimalField(decimal_places=2, default=0, help_text="Coût réel des matières consommées, déclaré par le Chef d'atelier.", max_digits=12)),
                ('cout_temps_machine_reel', models.DecimalField(decimal_places=2, default=0, help_text="Coût réel du temps machine consommé, déclaré par le Chef d'atelier.", max_digits=12)),
                ('marge_cible_pourcentage', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Marge cible attendue (%), par défaut 20 %.', max_digits=5)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('marge_reelle_pourcentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('ecart_prix_revient', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Coût réel total - prix de revient estimé au devis (positif = dépassement).', max_digits=12)),
                ('resultat', models.CharField(choices=[('BENEFICIAIRE', 'Bénéficiaire'), ('DEFICITAIRE', 'Déficitaire'), ('EQUILIBRE', "À l'équilibre")], default='EQUILIBRE', editable=False, max_length=15)),
                ('ecart_significatif', models.BooleanField(default=False, editable=False)),
                ('date_controle', models.DateTimeField(auto_now_add=True)),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_effectues', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_prix_revient', to='commandes.dossierfabrication')),
            ],
            options={
                'verbose_name': 'Contrôle du prix de revient',
                'verbose_name_plural': 'Contrôles du prix de revient',
                'db_table': 'controles_prix_revient',
                'ordering': ['-date_controle'],
            },
        ),
    ]
